### ISSUE TITLE
I want to use the google-chart offline in the sample code attached - help

### ISSUE THREAD

**Issue by kandirajav** [changkejun/google-chart-offline#3]
I want to embed the google charts offline in the attached files in index.handlebars page.

I tried my best to attach the google charts offline but failed to add it. Hope you could help me solve it.

if you could help me to add the offline google charts in this page. it will be of a great help. thanks in advance. 

[simple-express-app.zip](https://github.com/changkejun/google-chart-offline/files/3467852/simple-express-app.zip)

**Comment by changkejun** [comment]
1. It seems "public" is the static contents folder. So put "charts" folder in it. The folder should be "simple-express-app/public/charts" . And the url should be "/charts".
2. layout.hbs is the view. So I add js and script to show a chart.You can edit it for yourself.
[layout.zip](https://github.com/changkejun/google-chart-offline/files/3469796/layout.zip)
3. you can move the <div id="chart_div"></div> to where you want it be for example in the "index.hbs" file.

If something does not execute please tell me .

**Comment by changkejun** [comment]
[simple-express-app.zip](https://github.com/changkejun/google-chart-offline/files/3469818/simple-express-app.zip)
Here is all file.

**Comment by kandirajav** [comment]
Thanks for this solution. I had to struggle implementing the offline charts in the website and your solution will help me cut my working time. Thanks a lot for your solution.

**Comment by kandirajav** [comment]
The solution solved the issue I was facing for a week. Thanks.

**Comment by Glestencio** [comment]
Hello, i really liked your project, i find it really easily explained.

Nevertheless im having some issues using it on mvc5 c# proyect, when im in the index methods of my controllers using ". /charts/....." works well. But as soon as i call the gstatic loader from any other action the library tries to call "localhost...... /controllerName/charts/...." from the gstatic loader, what of course it will never find.

Any idea /fix to this?

The local copys are as in the example you made. 

Thanks in advance.

**Comment by changkejun** [comment]
I move your message to a new issue. I will try to answer your message in it.
-- It is so difficult to find your message in a closed issue.
