### ISSUE TITLE
Any way to use material charts with this

### ISSUE THREAD

**Issue by cspencer49519** [changkejun/google-chart-offline#4]
When trying to use the material type of chart, I get errors, as fiels are missing. namely:

All of the items from the third_party directory. I grabbed and these seem to load fine(dygraphs, webfontloader).
Some required files from offlineSaving/js, jsapi_compiled_line_module.js, jsapi_compiled_fw_module.js.

Any way to get these working? I grabbed the source and I get a couple errors:

23:57:10.346 TypeError: gvjs_e is not a function jsapi_compiled_fw_module.js:2:186
    <anonymous> http://192.168.0.29:3500/charts/offlineSaving/js/jsapi_compiled_fw_module.js:2

23:57:10.351 TypeError: gvjs_g is not a function jsapi_compiled_line_module.js:6:409

**Comment by changkejun** [comment]
Maybe you put offline files wrong path in your app.it is better to make sure offlineSample.html can run in your app at first.
Or attach your app sample here to let me give your some ideas.

**Comment by cspencer49519** [comment]
These files are completely missing from your source. I think they may need to be modified to work locally. Especially jsapi_compiled_fw_module.js and jsapi_compiled_line_module.js

**Comment by changkejun** [comment]
Then please copy and download them and add in your app folder according to the steps.
This repository is  only a idea, not a full copy.  I dont want make Mr google angry.

**Comment by cspencer49519** [comment]
Yes, that is what I am saying. I already have done that. There are no references tto "46" or "gstatic" in either of the two files that are throwing the error. Maybe these are a newer version or are not matching? Could you maybe have a look at these two files:

jsapi_compiled_fw_module.js
jsapi_compiled_line_module.js\

Thanks for your time

**Comment by changkejun** [comment]
Oh? What is the chart in your app? Give a name let me try it.

**Comment by changkejun** [comment]
material I found it.

**Comment by cspencer49519** [comment]
Yes, if you would like an example I found a working version 44 here:

https://www.dropbox.com/s/4cd7zbdvv2mlg8f/gstatic.zip?dl=0

**Comment by changkejun** [comment]
I found some urls like  the next when material.
https://fonts.googleapis.com/css?family=Roboto%7CRoboto:medium
it is not a static one. So offline is difficult......

Sorry for no help to you.
And thanks for your msg about material. 

Maybe  chart.js is more easy if offline using.
The next url is a comparison sample about google chart and chart js. 
https://efwgrp.github.io/efw4_chart/chartSampleTypes.html
If its good enough , you can download it. 
https://github.com/efwGrp/efw4_chart

**Comment by cspencer49519** [comment]
No worries, I'll use the 44 version I posted the link to, it's working fine with material. Thanks.
